language: python
python: 3.5 
addons:
  mariadb: '10.4'
before_install:
  - sudo apt-get install parallel
  - sudo mysql -e 'CREATE DATABASE IF NOT EXISTS test;'
  - sudo mysql -e "CREATE USER 'travis'@'localhost' IDENTIFIED BY 'travis';"
  - sudo mysql -e "GRANT ALL ON test.* TO 'travis'@'localhost';"
  - mkdir -p ~/.parallel
  - touch ~/.parallel/will-cite
install: pip install mysql-connector
before_script: cd tests
script: ./run_tests.sh